# Generated by Django 3.2.4 on 2021-06-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='cgv.Actor'),
        ),
        migrations.DeleteModel(
            name='Actors_movies',
        ),
    ]
